# Generated by Django 4.0.2 on 2022-02-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('ph_number', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('at_callcenter', models.BooleanField(default=True)),
                ('at_reception', models.BooleanField(default=False)),
                ('at_counselor', models.BooleanField(default=False)),
                ('at_operations', models.BooleanField(default=False)),
                ('branch_assign', models.CharField(blank=True, max_length=255, null=True)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('assign_time', models.CharField(blank=True, max_length=255, null=True)),
                ('isCallDiscard', models.BooleanField(default=False)),
                ('needsToFollow', models.BooleanField(default=False)),
                ('isDocumentMissing', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploades',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='upload/')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcenter.caller')),
            ],
        ),
    ]
