# Generated by Django 4.0.2 on 2022-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_remove_caller_at_callcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='isRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
